.\" Manpage for randomtext
.\" Contact andrew@rail5.org to correct errors or typos.
.TH man 1 "24 March 2023" "1.0" "randomtext man page"
.SH NAME
randomtext
.SH SYNOPSIS
randomtext
.SH DESCRIPTION
randomtext outputs random printable ASCII
.SH OPTIONS
  -l <length>
    Output a newline char every <length> characters.
.SH BUGS
No known bugs.
.SH AUTHOR
rail5 (andrew@rail5.org)
